server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
project:
  upload: upload/
base:
  url: http://localhost:8222
        
